project: 
  type: website
  output-dir: docs
  
website:
  title: "Application of Spatial Monitoring and Reporting Tool (SMART) for Improving Law-Enforcement Effectiveness at Nech Sar National Park, Ethiopia."
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/
      - icon: github
        href: https://github.com/ZerubabelDemeke/Habitat
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2023, Zeruabel Demeke"

format:
  html:
    theme: Minty
    toc: true

editor: source

